### PR TITLE
add ajax for select2 fields in group form and fix bug in issue #13

### PR DESCRIPTION
**Pull request by HaManhDong**

### CODE REVIEW

**Review by hieulq — APPROVED** [review]
will test tomorrow and report bug if need.

**Comment by hieulq** [comment]
@HaManhDong how about other select2 in other view?

**Comment by HaManhDong** [comment]
Because i have just finished ajax for select2 with potion api, so I push this first to receive your comment. I going to finish in other view tonight and push PR.

**Comment by hieulq** [comment]
@HaManhDong remember to fix issue #13

**Pull request merged**
